steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/mcmp-integration-qa/clair-scan-repo/app-image:${COMMIT_SHA}', 
           '.']
    id: docker-build-step
    waitFor: ['-'] 
  - name: 'gcr.io/cloud-builders/wget'
    args: ['-qO', 'yq', 'https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64']
  - name: 'ubuntu'
    args: ['chmod', 'a+x','yq']
  - name: 'ubuntu'
    args: ['ls', '-l' ]
  - name: 'ubuntu'
    args: ['./yq']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull arminc/clair-local-scan
        docker pull arminc/clair-db
        docker images
        docker run -d --name clair-db arminc/clair-db:latest
        docker run -p 6060:6060 --link clair-db:postgres -d --name clair arminc/clair-local-scan:latest
        docker ps
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sudo curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -o /usr/bin/clair-scanner
        sudo chmod 777 /usr/bin/clair-scanner
        clair-scanner -h
        ls
        docker images
        cat /etc/lsb-release
        sudo apt-get update
        sudo apt-get install -y iproute2
        
  - id: Docker images
    name: 'gcr.io/cloud-builders/docker'
    args: ['image',  'ls']
  - id: list files
    name: 'bash'
    script: |
      ls -l
  # Docker Push step
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/mcmp-integration-qa/clair-scan-repo/app-image:${COMMIT_SHA}']
artifacts:
  objects:
    location: 'gs://clair_scan_reports_bucket'
    paths: ['report.json']
options:
  logging: CLOUD_LOGGING_ONLY
