steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'us-central1-docker.pkg.dev/mcmp-integration-qa/clair-scan-repo/appimage:${COMMIT_SHA}', 
           '.']
    id: docker-build-step
    waitFor: ['-'] 
  - name: 'gcr.io/cloud-builders/wget'
    args: ['-qO', 'yq', 'https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64']
  - name: 'ubuntu'
    args: ['chmod', 'a+x','yq']
  - name: 'ubuntu'
    args: ['ls', '-l' ]
  - name: 'ubuntu'
    args: ['./yq']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull' , 'arminc/clair-local-scan']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['pull' , 'arminc/clair-db']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['images']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run' ,'-d','--name','clair-db', 'arminc/clair-db:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run' ,'-p','6060:6060','--link','clair-db:postgres','-d','--name','clair', 'arminc/clair-local-scan:latest']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['ps']
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update && apt-get install -y wget
        apt-get update && apt-get install -y curl
        _MY_IP=$(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')
        echo $_MY_IP
        _CLAIR_IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' clair)
        echo $_CLAIR_IP
        curl -L https://github.com/arminc/clair-scanner/releases/download/v12/clair-scanner_linux_amd64 -o /usr/bin/clair-scanner
        wget -qO clair-scanner https://github.com/arminc/clair-scanner/releases/download/v8/clair-scanner_linux_amd64 && chmod +x clair-scanner./clair-scanner --ip=$(docker network inspect bridge --format "{{range .IPAM.Config}}{{.Gateway}}{{end}}") appimage:latest || exit 0
        clair-scanner --ip $(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1') --clair http://$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' clair):6060 -t High --reportAll=false $appimage:$latest | tee ./report/clair-image-scan-report.tx
        clair-scanner -c http://localhost:6060 --ip $(ifconfig eth0 | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1')  --report="report.json" -t "High" appimage:latest
  - id: Docker images
    name: 'gcr.io/cloud-builders/docker'
    args: ['image',  'ls']
  - id: list files
    name: 'bash'
    script: |
      ls -l
  # Docker Push step
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'us-central1-docker.pkg.dev/mcmp-integration-qa/clair-scan-repo/appimage:${COMMIT_SHA}']
artifacts:
  objects:
    location: 'gs://clair_scan_report_bucket'
    paths: ['report.json']
options:
  logging: CLOUD_LOGGING_ONLY
